- name: Deploy Calculator App

  hosts: myhosts

  tasks:
    - name: Deploy Calculator App
      # run in background & interactive
      docker_container:
        name: calculator
        image: rohitshah1706/calculator
        state: started
        restart: yes
        interactive: yes
        detach: yes
